# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ruben/SageTea/sagetea-mail/upstream/qmf/examples/qtmail/searchviewbasephone.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchViewBase(object):
    def setupUi(self, SearchViewBase):
        SearchViewBase.setObjectName("SearchViewBase")
        SearchViewBase.resize(208, 362)
        self.gridlayout = QtWidgets.QGridLayout(SearchViewBase)
        self.gridlayout.setContentsMargins(0, 0, 0, 0)
        self.gridlayout.setSpacing(0)
        self.gridlayout.setObjectName("gridlayout")
        self.searchFrame = QtWidgets.QFrame(SearchViewBase)
        self.searchFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.searchFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchFrame.setLineWidth(0)
        self.searchFrame.setObjectName("searchFrame")
        self.gridlayout1 = QtWidgets.QGridLayout(self.searchFrame)
        self.gridlayout1.setObjectName("gridlayout1")
        self.TextLabel1 = QtWidgets.QLabel(self.searchFrame)
        self.TextLabel1.setObjectName("TextLabel1")
        self.gridlayout1.addWidget(self.TextLabel1, 0, 0, 1, 1)
        self.mailbox = QtWidgets.QComboBox(self.searchFrame)
        self.mailbox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.mailbox.setObjectName("mailbox")
        self.mailbox.addItem("")
        self.mailbox.addItem("")
        self.mailbox.addItem("")
        self.mailbox.addItem("")
        self.mailbox.addItem("")
        self.mailbox.addItem("")
        self.gridlayout1.addWidget(self.mailbox, 0, 1, 1, 1)
        self.TextLabel1_2 = QtWidgets.QLabel(self.searchFrame)
        self.TextLabel1_2.setObjectName("TextLabel1_2")
        self.gridlayout1.addWidget(self.TextLabel1_2, 1, 0, 1, 1)
        self.status = QtWidgets.QComboBox(self.searchFrame)
        self.status.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.status.setObjectName("status")
        self.status.addItem("")
        self.status.addItem("")
        self.status.addItem("")
        self.status.addItem("")
        self.status.addItem("")
        self.gridlayout1.addWidget(self.status, 1, 1, 1, 1)
        self.TextLabel1_2_2 = QtWidgets.QLabel(self.searchFrame)
        self.TextLabel1_2_2.setObjectName("TextLabel1_2_2")
        self.gridlayout1.addWidget(self.TextLabel1_2_2, 2, 0, 1, 1)
        self.fromLine = QtWidgets.QLineEdit(self.searchFrame)
        self.fromLine.setObjectName("fromLine")
        self.gridlayout1.addWidget(self.fromLine, 2, 1, 1, 1)
        self.TextLabel1_2_2_2 = QtWidgets.QLabel(self.searchFrame)
        self.TextLabel1_2_2_2.setObjectName("TextLabel1_2_2_2")
        self.gridlayout1.addWidget(self.TextLabel1_2_2_2, 3, 0, 1, 1)
        self.toLine = QtWidgets.QLineEdit(self.searchFrame)
        self.toLine.setObjectName("toLine")
        self.gridlayout1.addWidget(self.toLine, 3, 1, 1, 1)
        self.TextLabel1_2_2_3 = QtWidgets.QLabel(self.searchFrame)
        self.TextLabel1_2_2_3.setObjectName("TextLabel1_2_2_3")
        self.gridlayout1.addWidget(self.TextLabel1_2_2_3, 4, 0, 1, 1)
        self.subjectLine = QtWidgets.QLineEdit(self.searchFrame)
        self.subjectLine.setObjectName("subjectLine")
        self.gridlayout1.addWidget(self.subjectLine, 4, 1, 1, 1)
        self.TextLabel1_2_2_4 = QtWidgets.QLabel(self.searchFrame)
        self.TextLabel1_2_2_4.setObjectName("TextLabel1_2_2_4")
        self.gridlayout1.addWidget(self.TextLabel1_2_2_4, 5, 0, 1, 1)
        self.bodyLine = QtWidgets.QLineEdit(self.searchFrame)
        self.bodyLine.setObjectName("bodyLine")
        self.gridlayout1.addWidget(self.bodyLine, 5, 1, 1, 1)
        self.dateAfterGroupBox = QtWidgets.QGroupBox(self.searchFrame)
        self.dateAfterGroupBox.setCheckable(True)
        self.dateAfterGroupBox.setObjectName("dateAfterGroupBox")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.dateAfterGroupBox)
        self.vboxlayout.setObjectName("vboxlayout")
        self.dateAfterButton = QtWidgets.QDateEdit(self.dateAfterGroupBox)
        self.dateAfterButton.setEnabled(False)
        self.dateAfterButton.setObjectName("dateAfterButton")
        self.vboxlayout.addWidget(self.dateAfterButton)
        self.gridlayout1.addWidget(self.dateAfterGroupBox, 7, 0, 1, 2)
        self.dateBeforeGroupBox = QtWidgets.QGroupBox(self.searchFrame)
        self.dateBeforeGroupBox.setCheckable(True)
        self.dateBeforeGroupBox.setObjectName("dateBeforeGroupBox")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.dateBeforeGroupBox)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.dateBeforeButton = QtWidgets.QDateEdit(self.dateBeforeGroupBox)
        self.dateBeforeButton.setEnabled(False)
        self.dateBeforeButton.setObjectName("dateBeforeButton")
        self.vboxlayout1.addWidget(self.dateBeforeButton)
        self.gridlayout1.addWidget(self.dateBeforeGroupBox, 8, 0, 1, 2)
        self.gridlayout.addWidget(self.searchFrame, 0, 0, 1, 1)
        self.TextLabel1.setBuddy(self.mailbox)
        self.TextLabel1_2.setBuddy(self.status)
        self.TextLabel1_2_2.setBuddy(self.fromLine)
        self.TextLabel1_2_2_2.setBuddy(self.toLine)
        self.TextLabel1_2_2_3.setBuddy(self.subjectLine)
        self.TextLabel1_2_2_4.setBuddy(self.bodyLine)

        self.retranslateUi(SearchViewBase)
        self.dateAfterGroupBox.toggled['bool'].connect(self.dateAfterButton.setEnabled)
        self.dateBeforeGroupBox.toggled['bool'].connect(self.dateBeforeButton.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(SearchViewBase)
        SearchViewBase.setTabOrder(self.mailbox, self.status)
        SearchViewBase.setTabOrder(self.status, self.fromLine)
        SearchViewBase.setTabOrder(self.fromLine, self.toLine)
        SearchViewBase.setTabOrder(self.toLine, self.subjectLine)

    def retranslateUi(self, SearchViewBase):
        _translate = QtCore.QCoreApplication.translate
        SearchViewBase.setWindowTitle(_translate("SearchViewBase", "Search"))
        self.TextLabel1.setText(_translate("SearchViewBase", "In"))
        self.mailbox.setWhatsThis(_translate("SearchViewBase", "Select the mailbox to search for mail in."))
        self.mailbox.setItemText(0, _translate("SearchViewBase", "Any"))
        self.mailbox.setItemText(1, _translate("SearchViewBase", "Inbox"))
        self.mailbox.setItemText(2, _translate("SearchViewBase", "Outbox"))
        self.mailbox.setItemText(3, _translate("SearchViewBase", "Drafts"))
        self.mailbox.setItemText(4, _translate("SearchViewBase", "Sent"))
        self.mailbox.setItemText(5, _translate("SearchViewBase", "Trash"))
        self.TextLabel1_2.setText(_translate("SearchViewBase", "Status"))
        self.status.setWhatsThis(_translate("SearchViewBase", "Find mail with a matching flag."))
        self.status.setItemText(0, _translate("SearchViewBase", "Any"))
        self.status.setItemText(1, _translate("SearchViewBase", "Read"))
        self.status.setItemText(2, _translate("SearchViewBase", "Unread"))
        self.status.setItemText(3, _translate("SearchViewBase", "Replied"))
        self.status.setItemText(4, _translate("SearchViewBase", "Removed"))
        self.TextLabel1_2_2.setText(_translate("SearchViewBase", "From"))
        self.fromLine.setWhatsThis(_translate("SearchViewBase", "Input text that must occur in the from field."))
        self.TextLabel1_2_2_2.setText(_translate("SearchViewBase", "To"))
        self.toLine.setWhatsThis(_translate("SearchViewBase", "Input text that must occur in the to field."))
        self.TextLabel1_2_2_3.setText(_translate("SearchViewBase", "Subject"))
        self.subjectLine.setWhatsThis(_translate("SearchViewBase", "Input text that must occur in the subject."))
        self.TextLabel1_2_2_4.setText(_translate("SearchViewBase", "Body"))
        self.bodyLine.setWhatsThis(_translate("SearchViewBase", "Input text that must occur in the subject."))
        self.dateAfterGroupBox.setWhatsThis(_translate("SearchViewBase", "Include only mails after this date."))
        self.dateAfterGroupBox.setTitle(_translate("SearchViewBase", "After"))
        self.dateBeforeGroupBox.setWhatsThis(_translate("SearchViewBase", "Include only mails before this date."))
        self.dateBeforeGroupBox.setTitle(_translate("SearchViewBase", "Before"))
